[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/v1.0/proxy/*"
  to = "https://api.nexon.co.kr/kart/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
