export const ActionTypes = {
  GET_USER_INFO_BY_ID: 'GET_USER_INFO_BY_ID',
  GET_USER_INFO_BY_NAME: 'GET_USER_INFO_BY_NAME',
  GET_ALL_MATCH_LIST: 'GET_ALL_MATCH_LIST',
  GET_MATCH_LIST_BY_ID: 'GET_MATCH_LIST_BY_ID',
  GET_MATCH_DETAIL_BY_ID: 'GET_MATCH_DETAIL_BY_ID',
} as const;
